# Generated by Django 5.2.6 on 2025-09-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('video games', 'Video Games'), ('jersey', 'Jersey'), ('football shoes', 'Football Shoes'), ('souvenir', 'Souvenir'), ('training kit', 'Training Kit'), ('ball', 'Ball')], max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
